language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - find .
  - make INSTALL_ROOT=appdir install ; find appdir/
  - mkdir -p appdir/usr/share/applications ; cp thinkgui.desktop appdir/usr/share/applications # FIXME: Do this in the .pro file
  - mkdir -p appdir/usr/share/icons/hicolor/48x48/apps/ ; cp res/icon.png appdir/usr/share/icons/hicolor/48x48/apps/thinkgui.png # FIXME: Do this in the .pro file

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./thinkgui*.AppImage https://transfer.sh/thinkgui-git.$(git rev-parse --short HEAD)-x86_64.AppImage
